print('NAME= Divyanshu Pal')
print('Phone Number= 6387811379')
print('Gaurdian Name= Vinay Kumar Pal')
print('Nominee Name = Vinay Kumar Pal')
print('Account Type= Personal')
print('Account Balance= 10000')
